sleep_apnea.json\:\:$['states']['Wait\ Until\ Overnight\ Study']['complex_transition'][0]['distributions'][0]['distribution'] = 0.25
sleep_apnea.json\:\:$['states']['Wait\ Until\ Overnight\ Study']['complex_transition'][0]['distributions'][1]['distribution'] = 0.75
sleep_apnea.json\:\:$['states']['Appointment\ Delay']['complex_transition'][0]['distributions'][0]['distribution'] = 0.25
sleep_apnea.json\:\:$['states']['Appointment\ Delay']['complex_transition'][0]['distributions'][1]['distribution'] = 0.75
